spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/Ownhub
    username : root
    password : lalorsh6471!

    jpa:
      hibernate:
        ddl-auot : none

      show-sql: true


server:
  servlet:
    session:
      tracking-modes : cookie


